# Site settings
title: SLCC Tech Services
email: techserv@stlchristian.edu
description: > # this means to ignore newlines until "baseurl:"
  We are the IT department at St. Louis Christian College. Here is some
  of our techno-babble that you may or may not understand. Enjoy!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://stlchristian.github.io" # the base hostname & protocol for your site
twitter_username: stlchristian
github_username:  stlchristian

# Build settings
markdown: kramdown
highlighter: pygments
